# Generated by Django 4.2.4 on 2023-11-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_category_priority_study_mark_finance_commitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='concluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finance',
            name='entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mark',
            name='concluded',
            field=models.BooleanField(default=False),
        ),
    ]
