# Generated by Django 4.2.4 on 2023-11-03 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_commitment_concluded_alter_finance_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority', to='planner.priority'),
        ),
    ]
