# Generated by Django 4.2.4 on 2023-11-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_mark_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='paid',
        ),
        migrations.AddField(
            model_name='finance',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
