# Generated by Django 4.2.4 on 2023-11-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_remove_finance_paid_finance_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='price',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='pending',
        ),
        migrations.AddField(
            model_name='finance',
            name='concluded',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='entry',
            field=models.CharField(max_length=40),
        ),
    ]
