# Generated by Django 4.2.4 on 2023-11-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_rename_price_finance_value_remove_finance_pending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='concluded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
