# Generated by Django 4.2.4 on 2023-11-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_alter_study_concluded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='category',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
