# Generated by Django 4.2.4 on 2023-11-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='auction',
        ),
        migrations.AddField(
            model_name='study',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studyComment', to='planner.comment'),
        ),
    ]
