# Generated by Django 4.2.4 on 2023-11-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_remove_comment_auction_study_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.IntegerField(null=True),
        ),
    ]
