# Generated by Django 4.2.4 on 2023-11-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_rename_comments_study_comment_comment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='study',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studyComment', to='planner.study'),
        ),
    ]
