# Generated by Django 4.2.4 on 2023-11-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_remove_comment_course_remove_study_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='priority',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Commitment',
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
